<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> 

		<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
		<link rel="stylesheet" href="csstyle/popstyle.css"> 

		<script src="javascript/popup.js"></script>
		<title>Mon portfolio</title>
	</head>
<body class="cool">

<main>
	<div id="general" class="cool">
		
		<p class="choice"><button  id="switch"><img class="switcher" src="img/switch-off.png" alt='Abandonner' /></button><span  class="cool"> Design simple</span></p>
		<p class="choice"><button id="lvltop"><img src="img/trafficsmall.png" alt="Changement de classement" /></button><span  class="cool"> Changer le niveau</span></p>
		<h1 class="cool">Classement niveau I</h1>
		<div id="trez">Bienvenu sur le tableau des scores</div>
	</div>
<div class="loading-bar"></div>



</main>
</body>
